### ISSUE TITLE
Detect Left or Right yellow button 

### ISSUE THREAD

**Issue by dinami-k** [darryncampbell/DataWedge-Cordova-Sample#5]
Can i detect in javascript if a user press Left or Right Yeloow Button?
thanks

**Comment by darryncampbell** [comment]
Hi, are you looking to differentiate between whether the left or right yellow triggers are pressed?  If so then the answer would be no, unless you remap these keys on the device (Zebra offer a feature called KeyMapping Manager for this - http://techdocs.zebra.com/mx/keymappingmgr/).  If you just want to know when either trigger has been pressed, you could use the DataWedge Register_For_Notification API and register for SCANNER_STATUS: http://techdocs.zebra.com/datawedge/6-8/guide/api/registerfornotification/, but that API was added in DataWedge 6.8 so may not be available on your device, depending on which OS image you have.

**Comment by dinami-k** [comment]
Hi. yes, i am looking to differentiate between whether the left or right yellow triggers are pressed.
I work with TC-20 model and KeyMapping Manager not supported for this device.

My devices has Datawedge 6.6.49... can i update the datawdge version? how? dou you have a link with the steps?

thanks a lot.

**Comment by darryncampbell** [comment]
I'm afraid it is not possible to differentiate between the left and right trigger keys on TC20 as far as I know, you may need to find some other way of implementing your use case.

You can only update the DataWedge version by updating the entire OS (since DW is a system service).  If you have access, you can download OS updates from https://www.zebra.com/us/en/support-downloads/mobile-computers/handheld/tc20.html (though that requires a support contract).  The latest OS for TC20 is 4.14.30 LifeGuard Update 05 which contains DataWedge 6.9, according to the release notes, https://www.zebra.com/content/dam/zebra_new_ia/en-us/software/operating-system/tc20-operating-system/TC2X-0414300NG00M1-P5-release-notes.pdf

**Comment by esskar** [comment]
I added `filterActions` for `"com.symbol.button.L1"` and `"com.symbol.button.R1"`; now i get intents about the left or right buttons. more information can be found here: https://techdocs.zebra.com/emdk-for-android/8-0/samples/usingptt/
